#!/bin/bash
# Show help
show_help() {
   cat <<EOF
Usage: ./deploy [-e] [-h]
   -e   ember environment to build
   -h   displays basic help
EOF
}

# A POSIX variable
OPTIND=1

# Initialize our own variables:
environment="production"

while getopts "h?e:" opt; do
  case "$opt" in
    h|\?)
      show_help
      exit 0
      ;;
    e)  environment=$OPTARG
      ;;
  esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

ember build --environment=$environment
firebase deploy
